[Mellanox] Update FW if needed before fast-reboot (#513)
* [Mellanox] Update FW if needed before fast-reboot

This change aligns fast-reboot script with the master
at point 42582872ac0285fed53141d9e4b9a1a5652bb132
Unfortunatelly cannot be cherry-picked because original
commits also change other files

Signed-off-by: Andriy Moroz <c_andriym@mellanox.com>

* Return unique error if FW burn fails

Signed-off-by: Andriy Moroz <c_andriym@mellanox.com>

diff --git a/scripts/fast-reboot b/scripts/fast-reboot
--- a/scripts/fast-reboot
+++ b/scripts/fast-reboot
@@ -1,9 +1,13 @@
 #!/bin/bash
 
+REBOOT_USER=$(logname)
+REBOOT_TIME=$(date)
+REBOOT_CAUSE_FILE="/var/cache/sonic/reboot-cause.txt"
+
 # Check root privileges
 if [[ "$EUID" -ne 0 ]]
 then
-  echo "Please run as root"
+  echo "This command must be run as root" >&2
   exit
 fi
 
@@ -32,6 +36,24 @@ INITRD=$(echo $KERNEL_IMAGE | sed 's/vmlinuz/initrd.img/g')
 
 sonic_asic_type=$(sonic-cfggen -y /etc/sonic/sonic_version.yml -v asic_type)
 
+# Install new FW for mellanox platforms before control plane goes down
+# So on boot switch will not spend time to upgrade FW increasing the CP downtime
+if [[ "$sonic_asic_type" == "mellanox" ]]; then
+    echo "Prepare MLNX ASIC to fast reboot: install new FW if required"
+
+    MLNX_EXIT_SUCCESS="0"
+    MLNX_EXIT_FW_ERROR=100
+
+    MLNX_FW_UPGRADE_SCRIPT="/usr/bin/mlnx-fw-upgrade.sh"
+
+    ${MLNX_FW_UPGRADE_SCRIPT} --upgrade
+    MLNX_EXIT_CODE="$?"
+    if [[ "${MLNX_EXIT_CODE}" != "${MLNX_EXIT_SUCCESS}" ]]; then
+        echo "Failed to burn MLNX FW: errno=${MLNX_EXIT_CODE}"
+        exit "${MLNX_EXIT_FW_ERROR}"
+    fi
+fi
+
 # Load kernel into the memory
 /sbin/kexec -l "$KERNEL_IMAGE" --initrd="$INITRD" --append="$BOOT_OPTIONS"
 
@@ -50,7 +72,7 @@ docker kill lldp > /dev/null
 # Kill teamd, otherwise it gets down all LAGs
 docker kill teamd > /dev/null
 
-# syncd graceful stop is supported only for Broadcoms platforms only for now
+# syncd graceful stop is supported only for Broadcom platforms only for now
 if [[ "$sonic_asic_type" = 'broadcom' ]];
 then
     # Gracefully stop syncd
@@ -82,6 +104,11 @@ then
   systemctl stop nps-modules-`uname -r`.service
 fi
 
+# Update the reboot cause file to reflect that user issued 'fast-reboot' command
+# Upon next boot, the contents of this file will be used to determine the
+# cause of the previous reboot
+echo "User issued 'fast-reboot' command [User: ${REBOOT_USER}, Time: ${REBOOT_TIME}]" > ${REBOOT_CAUSE_FILE}
+
 # Wait until all buffers synced with disk
 sync
 sleep 1
@@ -89,4 +116,9 @@ sync
 
 # Reboot: explicity call Linux native reboot under sbin
 echo "Rebooting to $NEXT_SONIC_IMAGE..."
-/sbin/reboot
+exec /sbin/reboot
+
+# Should never reach here
+echo "fast-reboot failed!" >&2
+exit 1
+
